version: '3.4'
services:
  # ThingsBoard IoT Gateway Service Configuration
  tb-gateway:
    image: thingsboard/tb-gateway:3.4.6
    container_name: tb-gateway
    restart: always

    # Ports bindings - required by some connectors
    ports:
        - "5000:5000" # Comment if you don't use REST connector and change if you use another port
        # Uncomment and modify the following ports based on connector usage:
#        - "1052:1052" # BACnet connector
#        - "5026:5026" # Modbus TCP connector (Modbus Slave)
#        - "50000:50000/tcp" # Socket connector with type TCP
#        - "50000:50000/udp" # Socket connector with type UDP

    # Necessary mapping for Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Environment variables
    environment:
      - host=192.168.100.74
      - port=1883
      - accessToken=pr44fo3txwknekv2bqs9

    # Volumes bind
    volumes:
      - ./tb-gw/tb-gw-config:/thingsboard_gateway/config
      - ./tb-gw/tb-gw-logs:/thingsboard_gateway/logs
      - ./tb-gw/tb-gw-extensions:/thingsboard_gateway/extensions